export {_singerTypeData}
var _singerTypeData = {
    fathers:[
        {
        fatherNum:-1,
        fatherName:"推荐歌手"
        },
        {
            fatherNum:0,
            fatherName:"华语"
        },
        {
            fatherNum:1,
            fatherName:"欧美"
        },
        {
            fatherNum:2,
            fatherName:"日本"
        },
        {
            fatherNum:3,
            fatherName:"韩国"
        },
        {
            fatherNum:4,
            fatherName:"其他"
        }
    ],
    children:[
        {
            name:'华语男歌手',
            category:0,
            resourceType:1001
        },
        {
            name:'华语女歌手',
            category:0,
            resourceType:1002
        },
        {
            name:'华语组合/乐队',
            category:0,
            resourceType:1003
        },
        {
            name:'欧美男歌手',
            category:1,
            resourceType:2001
        },
        {
            name:'欧美女歌手',
            category:1,
            resourceType:2002
        },
        {
            name:'欧美组合/乐队',
            category:1,
            resourceType:2003
        },
        {
            name:'日本男歌手',
            category:2,
            resourceType:6001
        },
        {
            name:'日本女歌手',
            category:2,
            resourceType:6002
        },
        {
            name:'日本组合/乐队',
            category:2,
            resourceType:6003
        },
        {
            name:'韩国男歌手',
            category:3,
            resourceType:7001
        },
        {
            name:'韩国女歌手',
            category:3,
            resourceType:7002
        },
        {
            name:'韩国组合/乐队',
            category:3,
            resourceType:7003
        },
        {
            name:'其他男歌手',
            category:4,
            resourceType:4001
        },
        {
            name:'其他女歌手',
            category:4,
            resourceType:4002
        },
        {
            name:'其他组合/乐队',
            category:4,
            resourceType:4003
        },
    ]
}